num_classes: 80

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/lcliu/MSTARclutter/TrainingImages
    ann_file: /data/lcliu/MSTARclutter/trainingData.csv
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 8
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/lcliu/MSTARclutter/TestImages
    ann_file: /data/lcliu/MSTARclutter/testData.csv
    transforms:
      type: Compose
      ops: ~ 